blog/urls.py
from django.urls import path
from . import views as blog
from django.contrib.auth import views as auth_views

app_name = "blog"

urlpatterns = [
    
    # trang chủ
    path("", blog.HomeView.as_view(), name="home_blog"),
    # quản lý bài viết
    path('edit/<str:id>', blog.edit_article, name= "edit_article"),
    # tạo bài viết mới
    path('new/', blog.write_article, name= "write_article"),
    # xem bài viết cụ thể
    path('view/<str:article_id>/', blog.article_blogid, name= "article_blogid"),
    # xem danh sách các bài viết
    path('view_article/', blog.article_blog, name= "article_blog"),
    # xem danh sách các câu hỏi
    path('view_question/', blog.question_blog, name= "question_blog"),
    # đăng xuất
    path("logout/", blog.logout_function, name="logout_function"),
    
    # API trả về danh sách các bài viết
    path("view_all_article/", blog.ViewArticle.as_view()),
    
    path("view_article_by_id/", blog.MyArticle.as_view()),
    
    path("api_create_article/", blog.CreateArticle.as_view()),
    
    path("api_login/", blog.API_Login.as_view()),
    
    path("api_register/", blog.API_Register.as_view()),
    
    path("api_edit/", blog.API_Edit.as_view()),
]

system/urls.py
import django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("image_processing.urls")),
    path("blog/", include("blog.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User



import numpy as np
from datetime import date

# Create your models here.
# object_1.class_name.add(object_2) -> many to many

gender_choise = (
    ("MALE", "Male"),
    ("FEMALE", "Female")
)
type_blog = (
    ("trả lời", "hỏi"),
    ("bình luận", "đăng bài viết")
)
class Reporter(models.Model):
    
    reporter_id   = models.ForeignKey(User, on_delete= models.CASCADE)
    gender        = models.CharField(max_length = 20, choices = gender_choise, default = 'MALE')
    phone_number  = models.CharField(max_length= 12, unique= True)
    address       = models.CharField(max_length=100, default= "")
    company       = models.CharField(max_length=100, default= "")
    
    friends_list  = models.TextField(default= "", blank= True, null= True)
    blogs_list    = models.TextField(default= "", blank= True, null= True)
    question_list = models.TextField(default= "", blank= True, null= True)
    organization  = models.TextField(default= "", blank= True, null= True)
    
    def __str__(self):
        return self.reporter_id.last_name + " " + self.reporter_id.first_name
    
    
    def change_password(self, password):
        self.reporter_id.set_password(password)
        self.reporter_id.save()
        
        
    def follow(self, id_reporter):
        friends_list = str(self.friends_list).split('_')
        if id_reporter not in friends_list:
            friends_list.append(id_reporter)
            friends_list = '_'.join(friends_list)
            self.friends_list = friends_list
            self.save()
            
    
    def un_follow(self, id_reporter):
        friends_list = str(self.friends_list).split('_')
        if id_reporter in friends_list:
            np_friends = np.array(friends_list) 
            np_friends = np.delete(np_friends, np.where(np_friends == id_reporter))
            friends_list = '_'.join(list(np_friends))
            self.friends_list = friends_list
            self.save()
            

class Article(models.Model):
    
    title          = models.CharField(max_length= 100, blank= False, null= False)
    reporter       = models.ForeignKey(Reporter, on_delete=models.CASCADE)
    pub_date       = models.DateField()
    
    content        = models.TextField(default= "")
    number_view    = models.CharField(max_length= 100, default= "0")
    number_comment = models.CharField(max_length= 100, default= "0")
    up_vote        = models.CharField(max_length= 100, default= "0")
    down_vote      = models.CharField(max_length= 100, default= "0")
    
    tag            = models.TextField(default= "")  
    types_blog     = models.CharField(max_length = 20, choices = type_blog, default = 'trả lời')
    
    
    def __str__(self):
        return self.title + f" -- Tác giả[{self.reporter.reporter_id.username}]"
    
    
    def show_tag(self):
        str_tag = self.tag.split("#")[1:]
        for i in range(len(str_tag)):
            str_tag[i] = "#" + str_tag[i]
        return str_tag
        
    
    
    
    class Meta:
        ordering = ['-pub_date']
    
    
class Commented(models.Model):
    
    reporter = models.ForeignKey(Reporter, on_delete= models.CASCADE)
    article  = models.ForeignKey(Article, on_delete = models.CASCADE)
    
    content  = models.TextField(blank= False, null= False)
    
    pub_date = models.DateField(auto_now_add=True)
    # pub_date = models.DateField(default= date.today)
    
    def __str__(self):
        print(self.article.types_blog)
        return self.reporter.__str__() + " Đã " + self.article.types_blog + " " + self.article.__str__()
    
    
    
class Groups_User(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    group_name = models.CharField(max_length= 20)
    
    def __str__(self):
        return self.user.get_username() + " GROUPS[" + self.group_name + "]"

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest

# models
from blog.models import Reporter, Article, Groups_User
from django.contrib.auth.models import User


# logout
from django.contrib.auth import logout, authenticate, login


# API
from rest_framework.views import APIView
from rest_framework.response import Response


# Session
from django.contrib.sessions.models import Session

def process_name(name: str):
    try:
        name = name.strip()
        name = name.split()
        first, last = " ".join(name[:-1]), name[-1]
    except Exception as error:
        return (False, error)
    # print(first, last)
    return first, last

# Create your views here.
class HomeView(ListView):
    model = Article
    template_name = "blog/home_view/index.html"
    context_object_name = "articles"
    # paginate_by = 2




def article_blog(request):    
    objects = Article.objects.all()
    template = loader.get_template("blog/article_view/only_article.html")
    context = {
        "articles" : objects
    }
    return HttpResponse(template.render(context, request))

def question_blog(request):    
    objects = Article.objects.all()
    template = loader.get_template("blog/article_view/only_question.html")
    context = {
        "articles" : objects
    }
    return HttpResponse(template.render(context, request))


def article_blogid(request, article_id):    
    
    
    objects = Article.objects.filter(id= article_id)[0]
    # print(objects)
    
    template = loader.get_template("blog/article_view/content_article.html")
    context = {
        "objects" : objects
    }
      
    return HttpResponse(template.render(context, request))

def edit_article(request, id):    
    views = id
    # lấy session_id của người dùng đang đăng nhập
    user = request.session['_auth_user_id']
    
    # lấy đối tượng từ bảng User
    _user = User.objects.filter(id = user)[0]
    # lấy đối tượng từ bảng Reporter
    _reporter = Reporter.objects.filter(reporter_id= _user)[0]
    
    # lấy tất cả các bài viết của _user
    _article = Article.objects.filter(reporter= _reporter)
    _title = ""
    _pub_date = ""
    _content = ""
    _types_blog = ""
    _tags = ""
    save = None
    alert = False
    error_code = ""
    if views != "0":
        _article = Article.objects.filter(id= int(id))[0]
        _title = _article.title
        _pub_date = _article.pub_date
        _content  = _article.content
        _types_blog = _article.types_blog
        _tags = _article.tag
    
    if request.method == "POST":
        if "delete" in request.POST.keys():
            _article.delete()
            return redirect("/blog/edit/0")
        alert = True
        try:
            _article.title = request.POST['title']
            _article.pub_date = request.POST['pub_date']
            _article.content = request.POST['content']
            _article.types_blog = request.POST['tags']
            _article.tag = request.POST['types_blog']
            _article.save()
            save = "1"
            _article = Article.objects.filter(id= int(id))[0]
            _title = _article.title
            _pub_date = _article.pub_date
            _content  = _article.content
            _types_blog = _article.types_blog
            _tags = _article.tag
        except Exception as e:
            save = "2"
            error_code = e
            
    # print("SAVE", save)
    template = loader.get_template("blog/user/my_article.html")
    context = {
        "username" : _reporter.reporter_id.get_username(),
        "views" : views,
        "articles" : _article,
        "title" : _title,
        "pub_date" :  _pub_date,
        "content" : _content,
        "types_blog" : _types_blog,
        "tags" : _tags,
        "saves": save,
        "alert":alert,
        "error_code" : error_code
    }
    return HttpResponse(template.render(context, request))


def write_article(request):
    
    # lấy session_id của người dùng đang đăng nhập
    user = request.session['_auth_user_id']
    
    # lấy đối tượng từ bảng User
    _user = User.objects.filter(id = user)[0]
    # lấy đối tượng từ bảng Reporter
    _reporter = Reporter.objects.filter(reporter_id= _user)[0]
    
    Error = None
    status = 0
    _title = ""
    _pub_date = ""
    _content = ""
    _types_blog = ""
    _tags = ""
    # nếu người dùng ấn nút gửi
    if request.method == "POST":
        # lấy tiêu đề của bài viết
        _title = request.POST['title']
        # lấy ngày đăng bài
        _pub_date = request.POST['pub_date']
        # nội dung bài đăng
        _content  = request.POST['content']
        # kiểu bài đăng
        _types_blog = request.POST['types_blog']
        # lấy tags bài đăng
        _tags = request.POST['tags']
        
        new_blog = Article(title= _title,
                           reporter= _reporter,
                           pub_date= _pub_date,
                           content= _content,
                           number_view= 0,
                           number_comment= 0,
                           up_vote= 0,
                           down_vote= 0,
                           tag= _tags,
                           types_blog= _types_blog)
        
        try:
            new_blog.save()
            Error = "Đăng bài thành công"
            status = 1
        except Exception as e:
            Error = "Lỗi đăng bài: Error[" + str(e) + "]"
            status = 2
        # print(Error)
    
    
    template = loader.get_template("blog/user/article.html")
    if status == 1:
        _title = ""
        _pub_date = ""
        _content = ""
        _types_blog = ""
        _tags = ""
    context = {
        "username" : _user.get_username(),
        "status" : status,
        "alert" : Error,
        "title" : _title,
        "pub_date" :  _pub_date,
        "content" : _content,
        "types_blog" : _types_blog,
        "tags" : _tags
    }
      
    return HttpResponse(template.render(context, request))   


# đăng xuất
def logout_function(request):
    logout(request)
    return redirect('/')


class ViewArticle(APIView):
    def get(self, request):
        objects = Article.objects.all()
        index = 1
        _dict = {}
        for object in objects:
            tmp = object.__dict__
            del tmp['_state']
            _dict[str(index)] = tmp
            index += 1
        
        return Response({"article" : _dict})
    
class MyArticle(APIView):
    
    def get(self, request):
        objects = Article.objects.all()
        index = 1
        result = {}
        for object in objects:
            temp = object.__dict__
            del temp['_state']
            
            dem = 0
            for key in request.data.keys():
                if key in temp.keys() and temp[key] == request.data[key]:
                    dem += 1
            if dem == len(request.data.keys()):
                result[f"{index}"] = temp
                index+=1
            
        
        return Response({"article" : result})
    
class CreateArticle(APIView):
    
    def post(self, request):
        # print(request.session['_auth_user_id'])
        Error = "NONE"
        
        user = Session.objects.get(pk= request.data['session_key']).get_decoded().get('_auth_user_id')
        
        _user = User.objects.filter(id = user)[0]
        _reporter = Reporter.objects.filter(reporter_id= _user)[0]
        
        
        _title = request.data['title']
        # lấy ngày đăng bài
        _pub_date = request.data['pub_date']
        # nội dung bài đăng
        _content  = request.data['content']
        # kiểu bài đăng
        _types_blog = request.data['types_blog']
        # lấy tags bài đăng
        _tags = request.data['tags']
            
        try:
            new_blog = Article(title= _title,
                            reporter= _reporter,
                            pub_date= _pub_date,
                            content= _content,
                            number_view= 0,
                            number_comment= 0,
                            up_vote= 0,
                            down_vote= 0,
                            tag= _tags,
                            types_blog= _types_blog)
        
        
            new_blog.save()
            Error = "Đăng bài thành công"
        except Exception as e:
            Error = e
    

        return Response({"result" : Error})
    
    
class API_Login(APIView):
    def get(self, request):
        status = ""
        id_user = "-"
        username = request.data["Username"]
        password = request.data["Password"]
        user = authenticate(username= request.data["Username"], password= request.data["Password"])
        session_key = ""
        if user is not None:
            login(request, user)
            print(Session.objects.all())
            print("OK")
            status = "Đăng nhập thành công"
            session_key = ""
            session_list = Session.objects.all()
            for item in session_list:
                print("CALLING")
                uid = item.get_decoded().get('_auth_user_id')
                if uid is None:
                    continue
                user = User.objects.get(pk=uid)
                if user.username == username and user.check_password(password):
                    session_key = item.session_key
                    break
            
            
        else:
            status = "Đăng nhập không thành công"
        
        return Response({"result" : status, "session_key" : session_key})


class API_Register(APIView):
    
    def post(self, request):
        username = request.data['username']
        password = request.data['password']
        rpassword = request.data['rpassword']
        name = request.data['name']
        email = request.data['email']

templates/blog/user/article.html
{% extends 'blog/base/base.html' %}

{% load static %}



{% block title %}Tạo bài viết mới{% endblock %}

{% block exntends_css %}
<link rel="stylesheet" href={% static 'css/blog/user/user.css' %} />
{% endblock exntends_css %}


{% block content %}
{% include 'blog/component/nav_bar.html' %}


{% comment %} 

input, type="text", name = title, maxlength="100", required
input, type="text", name="pub_date", required
textarea, name="content/tag", cols="40", rows="10", required
      <select name="types_blog" id="id_types_blog">
  <option value="trả lời" selected>hỏi</option>

  <option value="bình luận">đăng bài viết</option>

</select>
{% endcomment %}




<div class="row g-0">
  <div class="col-sm-6 col-md-5">
    <form class="form-signin" method="POST">
      <h1 class="h3 mb-3 font-weight-normal">Bài viết</h1>
      {% csrf_token %}
      <div class='mt-4'>
        <label class="form-label" for="textAreaExample">Tiêu đề</label>
        <input name="title" id="inputTitle" maxlength="100" class="form-control" placeholder="" required value="{{title}}" autofocus="" type="text" onChange="markdown()">
      </div>
      <div class="mt-4">
        <label class="form-label" for="textAreaExample">Ngày phát hành</label>
        <input name="pub_date" id="inputPubDate" class="form-control" placeholder="" required value="{{pub_date}}" autofocus="" type="text" onChange="markdown()">
      </div>
    
      <div class="form-outline mt-4">
        <label class="form-label" for="textAreaExample">Nội dung</label>
        <textarea name= "content" class="form-control" id="textAreaExample1" cols="40" rows="10" value="{{content}}" onChange="markdown()"></textarea>
      </div>

      <div class="form-outline mt-4">
        <label class="form-label" for="textAreaExample">Tags</label>
        <textarea name= "tags" class="form-control" id="textAreaExample1" cols="40", rows="10" value="{{tags}}" onChange="markdown()"></textarea>
      </div>

      <div class='mt-4'>
        <label class="form-label" for="textAreaExample">Kiểu</label>
        <select  name="types_blog" class="form-select" aria-label="Default select example">
          <option  value="trả lời" {% if types_blog == 'trả lời'%}selected{% endif %}>hỏi</option>
          <option  value="bình luận" {% if types_blog == 'bình luận'%}selected{% endif %}>đăng bài viết</option>
        </select>
      </div>

      <div class='mt-4'>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Tạo</button>
      </div>
    </form>
  </div>
  <div class="col-6 col-md-7">




    <div class="card output_card mt-4">
      <div class="card-body">

        {% if alert %}
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
              <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
              </symbol>
              <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
              </symbol>
              <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
              </symbol>
            </svg>
            

            {% if status == 1 %}
              <div class="alert alert-success d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                <div>
                  {{alert}}
                </div>
              </div>
            {% elif status == 2 %}
              <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div>
                  {{alert}}
                </div>
              </div>
            {% endif %}
        {% else %}
          <div class='blogger center mx-auto' style="max-width: 683px">
            <div class='text-muted' id="author" >{{username}}</div>
            <div class='text-muted' id="pub_date_">Ngày phát hành</div>
            <h1 class="fw-bold pb-3" id="title">Tiêu đề</h1>
            <p id='out'>Nội dung</p>
          </div>
        {% endif %}

      </div>
    </div>

  </div>

</div>



{% endblock %}

{% block extends_js %}



<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src={% static 'js/blog/user/user.js' %}></script>
<script>
  function markdown() {
    document.getElementById('title').innerHTML = marked.parse(document.getElementById('inputTitle').value);
    document.getElementById('pub_date_').innerHTML = marked.parse(document.getElementById('inputPubDate').value);
    document.getElementById('out').innerHTML = marked.parse(" " + document.getElementById('textAreaExample1').value);
  };
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js">
</script>

<script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js" defer></script>
{% endblock extends_js %}


templates/blog/user/my_article.html
{% extends 'blog/base/base.html' %}
{% load static %}
{% block title %}Các bài viết của ... {% endblock %}


{% block exntends_css %}
<link rel="stylesheet" href={% static 'css/blog/user/my_article.css' %} />
{% endblock exntends_css %}

{% block content %}
{% include 'blog/component/nav_bar.html' %}



{% if  views == "0" %}
    <div class="container mt-4 custom">
        <div class="list-group list-group-light">
            {% for article in articles %}
                <a href="/blog/edit/{{article.id}}" class="list-group-item px-3 border-0"> 
                    <div class='row custom-list'>
                        <div class='col-8'>
                            <div class='card-body p-0'>
                                <div class="pb-2 text-body infscroll-author">
                                    Bạn {% if article.types_blog == 'trả lời' %}đã đặt câu hỏi{% else%}đã đăng bài viết{% endif %}
                                </div>
                                <h3 class="mb-1 text-body fw-bold" >
                                    {{article.title|truncatechars:50}}
                                </h3>
                                <h5 class='text-muted infscroll-date'>
                                    {{article.pub_date}}
                                </h5>
                            </div>
                        </div>
                        <div class='col-4'>
                            <img src={% static 'image/200x200.png' %} class="img-thumbnail" alt="..." style="width: 100px; height: 100px;">
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% else %}


<div class="row g-0 my_article">
    <div class="col-sm-6 col-md-5">
      <form class="form-signin" method="POST">
        <h1 class="h3 mb-3 font-weight-normal">Bài viết</h1>
        {% csrf_token %}
        <div class='mt-4'>
          <label class="form-label" for="textAreaExample">Tiêu đề</label>
          <input name="title" id="inputTitle" maxlength="100" class="form-control" placeholder="" required value="{{title}}" autofocus="" type="text" onChange="markdown()">
        </div>
        <div class="mt-4">
          <label class="form-label" for="textAreaExample">Ngày phát hành</label>
          <input name="pub_date" id="inputPubDate" class="form-control" placeholder="" required value="{{pub_date|date:"Y-m-d"}}" autofocus="" type="text" onChange="markdown()">
        </div>
      
        <div class="form-outline mt-4">
          <label class="form-label" for="textAreaExample">Nội dung</label>
          <textarea name= "content" class="form-control" id="textAreaExample1" cols="40" rows="10" onChange="markdown()">{{content}}</textarea>
        </div>
  
        <div class="form-outline mt-4">
          <label class="form-label" for="textAreaExample">Tags</label>
          <textarea name= "tags" class="form-control" id="textAreaExample1" cols="40", rows="10"  onChange="markdown()">{{tags}}</textarea>
        </div>
  
        <div class='mt-4'>
          <label class="form-label" for="textAreaExample">Kiểu</label>
          <select  name="types_blog" class="form-select" aria-label="Default select example">
            <option  value="trả lời" {% if types_blog == 'trả lời'%}selected{% endif %}>hỏi</option>
            <option  value="bình luận" {% if types_blog == 'bình luận'%}selected{% endif %}>đăng bài viết</option>
          </select>
        </div>
  
        <div class='mt-4'>
          <button class="btn btn-lg btn-primary btn-block" type="submit">Lưu</button>
          <button name = "delete" class="btn btn-lg btn-primary btn-block" type="submit">Xoá</button>
        </div>
      </form>
    </div>
    <div class="col-6 col-md-7">
  
  
  
  
      <div class="card output_card mt-4">
        <div class="card-body">
  
          {% if alert %}
              <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </symbol>
                <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                </symbol>
                <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </symbol>
              </svg>
              
  
              {% if saves == "1" %}
                <div class="alert alert-success d-flex align-items-center" role="alert">
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                  <div>
                     OK
                  </div>
                </div>
              {% elif saves == "2" %}
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                  <div>
                    {{error_code}}
                  </div>
                </div>

              {% else %}
              HIHI
              {% endif %}
          {% else %}
            <div class='blogger center mx-auto' style="max-width: 683px">
              <div class='text-muted' id="author" >{{username}}</div>
              <div class='text-muted' id="pub_date_">Ngày phát hành</div>
              <h1 class="fw-bold pb-3" id="title">Tiêu đề</h1>
              <p id='out'>Nội dung</p>
            </div>
          {% endif %}
  
        </div>
      </div>
  
    </div>
  
  </div>

{% endif %}

{% endblock %}

{% block extends_js %}



<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src={% static 'js/blog/user/user.js' %}></script>
<script>
  function markdown() {
    document.getElementById('title').innerHTML = marked.parse(document.getElementById('inputTitle').value);
    document.getElementById('pub_date_').innerHTML = marked.parse(document.getElementById('inputPubDate').value);
    document.getElementById('out').innerHTML = marked.parse(" " + document.getElementById('textAreaExample1').value);
  };
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js">
</script>

<script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js" defer></script>
{% endblock extends_js %}