blog/urls.py
from django.urls import path
from . import views as blog
from django.contrib.auth import views as auth_views

app_name = "blog"

urlpatterns = [
    
    # trang chủ
    path("", blog.HomeView.as_view(), name="home_blog"),
    # quản lý bài viết
    path('edit/<str:id>', blog.edit_article, name= "edit_article"),
    # tạo bài viết mới
    path('new/', blog.write_article, name= "write_article"),
    # xem bài viết cụ thể
    path('view/<str:article_id>/', blog.article_blogid, name= "article_blogid"),
    # xem danh sách các bài viết
    path('view_article/', blog.article_blog, name= "article_blog"),
    # xem danh sách các câu hỏi
    path('view_question/', blog.question_blog, name= "question_blog"),
    # đăng xuất
    path("logout/", blog.logout_function, name="logout_function"),
    
    # API trả về danh sách các bài viết
    path("view_all_article/", blog.ViewArticle.as_view()),
    
    path("view_article_by_id/", blog.MyArticle.as_view()),
    
    path("api_create_article/", blog.CreateArticle.as_view()),
    
    path("api_login/", blog.API_Login.as_view()),
    
    path("api_register/", blog.API_Register.as_view()),
    
    path("api_edit/", blog.API_Edit.as_view()),
]

image_processing/urls.py
from django.urls import path
from . import views as img_p
from django.contrib.auth import views as auth_views

app_name = "image_processing"

urlpatterns = [
    path("", img_p.home, name="session"),
    path("brightness/", img_p.brightness, name="brightness"),
    path("contrast/", img_p.contrast, name="contrast"),
    path("kmeans/", img_p.kmeans, name="kmeans"),
    path("upload/", img_p.upload, name="upload"),
    path("login/", img_p.login_function, name="login_function"),
    path("logout/", img_p.logout_function, name="logout_function"),
    path("register/", img_p.register, name="register"),
    # path('logout/', auth_views.LogoutView.as_view(template_name='images/login_function.html'), name='logout'),
]

system/urls.py
import django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("image_processing.urls")),
    path("blog/", include("blog.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

image_processing/models.py
from django.db import models
from PIL import Image
import numpy as np
from image_processing.process import ProcessImage
from io import BytesIO
from django.core.files.base import ContentFile

# Create your models here.

Action = (
    ('Brightness', 'b'),
    ('Contrast', 'c'),
    ('Kmeans', 'k')
)


class ImageUpload(models.Model):
    author  = models.CharField(max_length= 150, primary_key=True)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    origin  = models.ImageField(upload_to= "")
    
    # def save(self, *args, **kwargs):
        
    #     current_img = Image.open(self.origin.url)
    #     image = np.array(current_img)
    #     output = ProcessImage(image, self.types).process()
    #     current_img = Image.fromarray(output)
        
    #     buffer = BytesIO()
    #     current_img.save(buffer, format='png')
    #     img_png = buffer.getvalue()
    #     self.process.save(str(self.process), ContentFile(img_png), save=False)

    #     super().save(*args, **kwargs)
    
class StoreSession(models.Model):
    author = models.CharField(max_length= 150, primary_key=True)
    session_key  = models.CharField(max_length= 40)
    
    
    def __str__(self):
        return self.author
    

templates/images/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}{{user}}{% endblock %}</title>
        {% block style %}{% endblock %}
        {% block js %}{% endblock %}
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	</head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#"> Xử lý ảnh</a>
            <ul class="nav nav-pills">
                <li class="nav-item">
                    {% block nav1 %}<a class="nav-link" href={% url 'image_processing:brightness' %}>Độ sáng</a>{% endblock %}
                </li>
                <li class="nav-item">
                    {% block nav2 %}<a class="nav-link" href={% url 'image_processing:contrast' %}>Tương phản</a>{% endblock %}
                </li>
                <li class="nav-item">
                    {% block nav3 %}<a class="nav-link" href={% url 'image_processing:kmeans' %}>Phân cụm</a>{% endblock %}
                </li>
                <li class="nav-item">
                    {% block nav4 %}<a class="nav-link" href={% url 'image_processing:upload' %}>Upload</a>{% endblock %}
                </li>
                <li class="nav-item">
                    {% block nav5 %}<a class="nav-link" href={% url 'image_processing:logout_function' %}>Đăng xuất</a>{% endblock %}
                </li>
              </ul>
        </nav>
        {% block content %}{% endblock %}
	</body>
</html>

templates/images/brightness.html
{% extends 'images/base.html' %}

{% load static %}

{% block title %}Tăng giảm độ sáng{% endblock %}

{% block style %}

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

#rangeValue {
    position: relative;
    display: block;
    text-align: center;
    font-size: 3em;
    color: #999;
    font-weight: 400;
}
.range {
    width: 350px;
    height: 15px;
    -webkit-appearance: none;
    background: #111;
    outline: none;
    border-radius: 15px;
    overflow: hidden;
    box-shadow: inset 0 0 5px rgba(0, 0, 0, 1);
}
.range::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 15px;
    height: 15px;
    border-radius: 50%;
    background: #a1baff;
    cursor: pointer;
    border: 4px solid #333;
    box-shadow: -407px 0 0 400px #b2d27b;
  }
</style>


{% endblock %}

{% block js %}
<script type="text/javascript">
    function rangeSlidecurrent_range(value) {
        document.getElementById('rangeValue1').innerHTML = value;
    };
    function rangeSlidecurrent_alpha(value) {
        document.getElementById('rangeValue2').innerHTML = value;
    };
</script>
{% endblock %}

{% block nav1 %}<a class="nav-link active" aria-current="page" href={% url 'image_processing:brightness' %}>Độ sáng</a>{% endblock %}


{% block content %}
<div class='container text-center mt-3'>
    <img
        {% comment %} src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" {% endcomment %}
        {% comment %} src = "{% static 'image/default.webp' %}" {% endcomment %}
        src = "data:image/jpg;base64, {{brightness}}"
        class="img-thumbnail"
        alt="Bạn chưa tải ảnh lên cơ sở dữ liệu"
    />
</div>
<div class='container'>
    <form method='post' class="form-signin text-center">
        {% csrf_token %}
        {% if is_image %}
        <label for="customRange" class="form-label" id="rangeValue1" name="show_range_output">{{current_range}}</label>
        <div>
            <input class="range" type="range" name = "rangeValue_in" value={{current_range}} min="-255" max="255" onChange="rangeSlidecurrent_range(this.value)" onmousemove="rangeSlidecurrent_range(this.value)" />
        </div>
        <label for="customRange" class="form-label" id="rangeValue2" name="show_alpha_output">{{current_alpha}}</label>
        <div>
            <input class="range" type="range" name = "show_alpha" value={{current_alpha}} min="1" max="10" onChange="rangeSlidecurrent_alpha(this.value)" onmousemove="rangeSlidecurrent_alpha(this.value)"/>
        </div>
        <button class="btn mt-20 w-50" type="submit">Đổi</button>
        {% endif %}
    </form>
</div> 
{% endblock %}

templates/images/contrast.html
{% extends 'images/base.html' %}

{% load static %}

{% block title %}Tăng giảm độ tương phản{% endblock %}

{% block nav2 %}<a class="nav-link active" aria-current="page" href={% url 'image_processing:contrast' %}>Tương phản</a>{% endblock %}

templates/images/edges.html
{% extends 'images/base.html' %}

{% load static %}

{% block title %}Tìm biên{% endblock %}

{% block nav2 %}<a class="nav-link active" aria-current="page" href={% url 'edges' %}>Tìm biên</a>{% endblock %}


{% block content %}

<div class="d-flex justify-content-center">

    <div class='container text-center mt-3'>
        <img
            src = "data:image/jpg;base64, {{ origin_image }}"
            class="img-thumbnail"
            alt="Bạn chưa tải ảnh lên cơ sở dữ liệu hoặc bị lỗi"
        />
    </div>

    <div class='container text-center mt-3'>
        <img
            src = "data:image/jpg;base64, {{ frame_b64 }}"
            class="img-thumbnail"
            alt="Bạn chưa tải ảnh lên cơ sở dữ liệu hoặc bị lỗi"
        />
    </div>

</div>


{% endblock %}

templates/images/kmeans.html
{% extends 'images/base.html' %}

{% load static %}

{% block title %}Phân cụm{% endblock %}

{% block nav3 %}<a class="nav-link active" aria-current="page" href={% url 'image_processing:kmeans' %}>Phân cụm</a>{% endblock %}

{% block style %}

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

#rangeValue {
    position: relative;
    display: block;
    text-align: center;
    font-size: 3em;
    color: #999;
    font-weight: 400;
}
.range {
    width: 350px;
    height: 15px;
    -webkit-appearance: none;
    background: #111;
    outline: none;
    border-radius: 15px;
    overflow: hidden;
    box-shadow: inset 0 0 5px rgba(0, 0, 0, 1);
}
.range::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 15px;
    height: 15px;
    border-radius: 50%;
    background: #a1baff;
    cursor: pointer;
    border: 4px solid #333;
    box-shadow: -407px 0 0 400px #b2d27b;
  }
</style>


{% endblock %}


{% block js %}
<script type="text/javascript">
    function rangeSlideK(value) {
        document.getElementById('rangeValue1').innerHTML = "K = " + value;
    };
</script>
{% endblock %}

{% block content %}
<div class='container text-center mt-3'>
    <img
        {% comment %} src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" {% endcomment %}
        {% comment %} src = "{% static 'image/default.webp' %}" {% endcomment %}
        src = "data:image/jpg;base64, {{url_image}}"
        class="img-thumbnail"
        alt="Bạn chưa tải ảnh lên cơ sở dữ liệu"
    />
</div>
<div class='container'>
    <form method='post' class="form-signin text-center">
        {% csrf_token %}
        {% if is_image %}
        <label for="customRange" class="form-label" id="rangeValue1" name="show_range">K = {{current_k}}</label>
        <div>
            <input class="range" type="range" name = "k_centroids" value={{current_k}} min="1" max="10" onChange="rangeSlideK(this.value)" onmousemove="rangeSlideK(this.value)" />
        </div>
            <button class="btn mt-20 w-50" type="submit">Đổi</button>
        {% endif %}
    </form>
</div> 
{% endblock %}

templates/images/login_imgp.html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Signin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    


<style>

html,
body {
    height: 100%;
}

body {
    display: -ms-flexbox;
    display: -webkit-box;
    display: flex;
    -ms-flex-align: center;
    -ms-flex-pack: center;
    -webkit-box-align: center;
    align-items: center;
    -webkit-box-pack: center;
    justify-content: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
}

.form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}

.form-signin .checkbox {
    font-weight: 400;
}

.form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
}

.form-signin .form-control:focus {
    z-index: 2;
}

.form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}

        

</style>


  </head>
  <body class="text-center">
    <form class="form-signin" method="POST" action="{% url 'login_function' %}">
      <h1 class="h3 mb-3 font-weight-normal">Login</h1>

      {% if errors %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class='error-code'>
              Đăng nhập không thành công
            </div>
          </div>
      {% endif %}


      {% csrf_token %}
      <input name="Username" id="inputUsername" class="form-control" placeholder="Username" required="" autofocus="" type="username">
      <input name="Password" id="inputPassword" class="form-control mt-2" placeholder="Password" required="" type="password">
      <button name="btn_signin" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
  </body>
</html>


templates/images/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Signin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    


<style>

html,
body {
    height: 100%;
}

body {
    display: -ms-flexbox;
    display: -webkit-box;
    display: flex;
    -ms-flex-align: center;
    -ms-flex-pack: center;
    -webkit-box-align: center;
    align-items: center;
    -webkit-box-pack: center;
    justify-content: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
}

.form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}

.form-signin .checkbox {
    font-weight: 400;
}

.form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
}

.form-signin .form-control:focus {
    z-index: 2;
}

.form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
    border-radius: 1px;
}

.form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}

#inputUsername, #inputPassword, #inputFirstname{
    border-radius: 10px;
}
</style>


  </head>
  <body class="text-center">
    <form class="form-signin" method="POST" action="{% url 'image_processing:register' %}">
      <h1 class="h3 mb-3 font-weight-normal">Register</h1>

      <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
          <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </symbol>
          <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
          </symbol>
          <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </symbol>
      </svg>
      {% if errors == True %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
            Đăng nhập thành công
            </div>
        </div>
      {% elif errors != True and errors is not None %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class='error-code'>
                {{errors}}
            </div>
        </div>
      {% endif %}


      {% csrf_token %}
      <input name="username" id="inputUsername" class="form-control" placeholder="Tên đăng nhập" required="" autofocus="" type="username">
      <input name="password" id="inputPassword" class="form-control mt-2" placeholder="Mật khẩu" required="" type="password">
      <input name="rpassword" id="inputPassword" class="form-control mt-2" placeholder="Nhập lại mật khẩu" required="" type="password" >
      <input name="name" id="inputFirstname" class="form-control mt-2" placeholder="Họ và tên" required="" type="text">
      <input name="email" id="inputFirstname" class="form-control mt-2" placeholder="Email" required="" type="email">
      <input name="phone" id="inputFirstname" class="form-control mt-2" placeholder="Số điện thoại" required=""  type="text">
      <input name="address" id="inputFirstname" class="form-control mt-2" placeholder="Địa chỉ" required="" type="text">
      <input name="company" id="inputFirstname" class="form-control mt-2" placeholder="Tổ chức" required="" type="text">
      <div class='mt-2'>
        <select  name="gender" class="form-select" aria-label="Default select example">
          <option  name="gender" value="MALE">Nam</option>
          <option  name="gender" value="FEMALE">Nữ</option>
        </select>
      </div>
      <button name="btn_signin" class="btn btn-lg btn-primary btn-block mt-2" type="submit">Đăng kí</button>
      <div class='mt-3'>
        <a href="{% url 'image_processing:login_function' %}">Đăng nhập</a>
      </div>
    </form>
  </body>
</html>

templates/images/upload.html
{% extends 'images/base.html' %}

{% load static %}

{% block title %}Tải ảnh{% endblock %}

{% block style %}
<style>
    body {
        font-family: sans-serif;
        background-color: #eeeeee;
      }
      
      .file-upload {
        background-color: #ffffff;
        width: 600px;
        margin: 0 auto;
        padding: 20px;
      }
      
      .file-upload-btn {
        width: 100%;
        margin: 0;
        color: #fff;
        background: #1FB264;
        border: none;
        padding: 10px;
        border-radius: 4px;
        border-bottom: 4px solid #15824B;
        transition: all .2s ease;
        outline: none;
        text-transform: uppercase;
        font-weight: 700;
      }
      
      .file-upload-btn:hover {
        background: #1AA059;
        color: #ffffff;
        transition: all .2s ease;
        cursor: pointer;
      }
      
      .file-upload-btn:active {
        border: 0;
        transition: all .2s ease;
      }
      
      .file-upload-content {
        display: none;
        text-align: center;
      }
      
      .file-upload-input {
        position: absolute;
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        outline: none;
        opacity: 0;
        cursor: pointer;
      }
      
      .image-upload-wrap {
        margin-top: 20px;
        border: 4px dashed #1FB264;
        position: relative;
      }
      
      .image-dropping,
      .image-upload-wrap:hover {
        background-color: #1FB264;
        border: 4px dashed #ffffff;
      }
      
      .image-title-wrap {
        padding: 0 15px 15px 15px;
        color: #222;
      }
      
      .drag-text {
        text-align: center;
      }
      
      .drag-text h3 {
        font-weight: 100;
        text-transform: uppercase;
        color: #15824B;
        padding: 60px 0;
      }
      
      .file-upload-image {
        max-height: 200px;
        max-width: 200px;
        margin: auto;
        padding: 20px;
      }
      
      .remove-image {
        width: 200px;
        margin: 0;
        color: #fff;
        background: #cd4535;
        border: none;
        padding: 10px;
        border-radius: 4px;
        border-bottom: 4px solid #b02818;
        transition: all .2s ease;
        outline: none;
        text-transform: uppercase;
        font-weight: 700;
      }
      
      .remove-image:hover {
        background: #c13b2a;
        color: #ffffff;
        transition: all .2s ease;
        cursor: pointer;
      }
      
      .remove-image:active {
        border: 0;
        transition: all .2s ease;
      }
</style>
{% endblock %}

{% block js %}
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
      
          var reader = new FileReader();
      
          reader.onload = function(e) {
            $('.image-upload-wrap').hide();
      
            $('.file-upload-image').attr('src', e.target.result);
            $('.file-upload-content').show();
      
            $('.image-title').html(input.files[0].name);
          };
      
          reader.readAsDataURL(input.files[0]);
      
        } else {
          removeUpload();
        }
      }
      
      function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
      }
      $('.image-upload-wrap').bind('dragover', function () {
              $('.image-upload-wrap').addClass('image-dropping');
          });
          $('.image-upload-wrap').bind('dragleave', function () {
              $('.image-upload-wrap').removeClass('image-dropping');
      });
      
</script>
{% endblock %}

{% block nav4 %}<a class="nav-link active" aria-current="page" href={% url 'image_processing:upload' %}>Upload</a>{% endblock %}


{% block content %}
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<div class='container'>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="file-upload">
            <input name="author" maxlength="150" required id="id_author" class="form-control" placeholder="Author" required="" autofocus="" type="text">
            </br>
            <button name = "origin" class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>
          
            <div class="image-upload-wrap">
              <input class="file-upload-input" type="file" name="origin" accept="image/*" required id="id_origin" onchange="readURL(this);"/>
              <div class="drag-text">
                <h3>Drag and drop a file or select add Image</h3>
              </div>
            </div>
            <div class="file-upload-content">
              <img class="file-upload-image" src="#" alt="your image" />
              <div class="image-title-wrap">
                <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
              </div>
            </div>
          </div> 
          <div class="d-flex justify-content-center">
            <button class="btn" type="submit">Upload</button>
          </div>
    </form>
</div> 



{% endblock %}